/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smiu;


import static com.oracle.webservices.internal.api.databinding.DatabindingModeFeature.ID;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import static smiu.DB.connect;

/**
 *
 * @author Syed Taqi
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    Connection con;
    public AdminPage() {
        initComponents();
        
        con = DB.connect();
    }

    
    PreparedStatement st;
    ResultSet rs;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBtnSignout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBtnUploadTranscript = new javax.swing.JButton();
        jBtnUploadDegree = new javax.swing.JButton();
        jBtStudentRecords = new javax.swing.JButton();
        jBtnUpdateDelete = new javax.swing.JButton();
        jBtnIssueTranscript = new javax.swing.JButton();
        jBtnNonIssueTranscript = new javax.swing.JButton();
        jBtnIssueDegree = new javax.swing.JButton();
        jBtnNotIssueDegree = new javax.swing.JButton();
        jBtnReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpg"))); // NOI18N

        jBtnSignout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnSignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        jBtnSignout.setText("SIGN OUT");
        jBtnSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSignoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Forte", 1, 30)); // NOI18N
        jLabel2.setText("NAVIGATION BAR");

        jBtnUploadTranscript.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnUploadTranscript.setText("Upload Transcripts");
        jBtnUploadTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUploadTranscriptActionPerformed(evt);
            }
        });

        jBtnUploadDegree.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnUploadDegree.setText("Upload Degrees");
        jBtnUploadDegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUploadDegreeActionPerformed(evt);
            }
        });

        jBtStudentRecords.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtStudentRecords.setText("Student Records");
        jBtStudentRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtStudentRecordsActionPerformed(evt);
            }
        });

        jBtnUpdateDelete.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnUpdateDelete.setText("Update & Delete ");
        jBtnUpdateDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateDeleteActionPerformed(evt);
            }
        });

        jBtnIssueTranscript.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnIssueTranscript.setText("Issue Transcripts");
        jBtnIssueTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIssueTranscriptActionPerformed(evt);
            }
        });

        jBtnNonIssueTranscript.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnNonIssueTranscript.setText("Non Issue Transcripts");
        jBtnNonIssueTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNonIssueTranscriptActionPerformed(evt);
            }
        });

        jBtnIssueDegree.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnIssueDegree.setText("Issue Degrees");
        jBtnIssueDegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIssueDegreeActionPerformed(evt);
            }
        });

        jBtnNotIssueDegree.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnNotIssueDegree.setText("Non Issue Degrees");
        jBtnNotIssueDegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNotIssueDegreeActionPerformed(evt);
            }
        });

        jBtnReport.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnReport.setText("Report");
        jBtnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnSignout)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnUploadTranscript, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnUploadDegree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtStudentRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnUpdateDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnIssueTranscript, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnNonIssueTranscript, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtnIssueDegree, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(jBtnNotIssueDegree, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(jBtnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1138, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnSignout)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnUploadTranscript)
                        .addGap(26, 26, 26)
                        .addComponent(jBtnUploadDegree)
                        .addGap(26, 26, 26)
                        .addComponent(jBtStudentRecords)
                        .addGap(29, 29, 29)
                        .addComponent(jBtnUpdateDelete)
                        .addGap(34, 34, 34)
                        .addComponent(jBtnIssueTranscript)
                        .addGap(30, 30, 30)
                        .addComponent(jBtnNonIssueTranscript)
                        .addGap(34, 34, 34)
                        .addComponent(jBtnIssueDegree)
                        .addGap(35, 35, 35)
                        .addComponent(jBtnNotIssueDegree)
                        .addGap(34, 34, 34)
                        .addComponent(jBtnReport)
                        .addGap(0, 161, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSignoutActionPerformed
        AdminLogin Info = new AdminLogin();
        Info.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnSignoutActionPerformed

    private void jBtnUploadTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUploadTranscriptActionPerformed
        Marks_Entry Info = new Marks_Entry();
        Info.setVisible(true);
    }//GEN-LAST:event_jBtnUploadTranscriptActionPerformed

    private void jBtnIssueDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIssueDegreeActionPerformed
         IssueDegree Info = new IssueDegree();
         Info.setVisible(true);
    }//GEN-LAST:event_jBtnIssueDegreeActionPerformed

    private void jBtnUploadDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUploadDegreeActionPerformed
        DegreeConditions Info = new DegreeConditions();
        Info.setVisible(true);
    }//GEN-LAST:event_jBtnUploadDegreeActionPerformed

    private void jBtnNotIssueDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNotIssueDegreeActionPerformed
        NotIssueDegree Info = new NotIssueDegree();
        Info.setVisible(true);
    }//GEN-LAST:event_jBtnNotIssueDegreeActionPerformed

    private void jBtStudentRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtStudentRecordsActionPerformed
       StudentRecord Info = new StudentRecord();
       Info.setVisible(true);
    }//GEN-LAST:event_jBtStudentRecordsActionPerformed

    private void jBtnIssueTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIssueTranscriptActionPerformed
        IssueTranscript Info = new IssueTranscript();
        Info.setVisible(true);
    }//GEN-LAST:event_jBtnIssueTranscriptActionPerformed

    private void jBtnNonIssueTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNonIssueTranscriptActionPerformed
        NotIssueTranscript Info = new NotIssueTranscript();
        Info.setVisible(true);
    }//GEN-LAST:event_jBtnNonIssueTranscriptActionPerformed

    private void jBtnUpdateDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateDeleteActionPerformed
        UpdateDelete Info = new UpdateDelete();
        Info.setVisible(true);
    }//GEN-LAST:event_jBtnUpdateDeleteActionPerformed

    private void jBtnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReportActionPerformed
        try{
        JasperDesign design = JRXmlLoader.load("C:\\Users\\Syed Taqi\\Documents\\NetBeansProjects\\SMIU\\src\\smiu\\StudentReport.jrxml");
        String query = "SELECT\n" +
"     firstsemetermarks.`ID` AS firstsemetermarks_ID,\n" +
"     firstsemetermarks.`Subject1` AS firstsemetermarks_Subject1,\n" +
"     firstsemetermarks.`Subject2` AS firstsemetermarks_Subject2,\n" +
"     firstsemetermarks.`Subject3` AS firstsemetermarks_Subject3,\n" +
"     firstsemetermarks.`Subject4` AS firstsemetermarks_Subject4,\n" +
"     firstsemetermarks.`Subject5` AS firstsemetermarks_Subject5\n" +
"FROM\n" +
"     `firstsemetermarks` firstsemetermarks";
        JRDesignQuery newQuery = new JRDesignQuery();
        newQuery.setText(query);
        
        design.setQuery(newQuery);
        
        JasperReport report = JasperCompileManager.compileReport(design);
        JasperPrint print = JasperFillManager.fillReport(report, null, con);
        JasperViewer.viewReport(print);
        }catch(Exception e){
        System.out.println(e);
       }
    }//GEN-LAST:event_jBtnReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtStudentRecords;
    private javax.swing.JButton jBtnIssueDegree;
    private javax.swing.JButton jBtnIssueTranscript;
    private javax.swing.JButton jBtnNonIssueTranscript;
    private javax.swing.JButton jBtnNotIssueDegree;
    private javax.swing.JButton jBtnReport;
    private javax.swing.JButton jBtnSignout;
    private javax.swing.JButton jBtnUpdateDelete;
    private javax.swing.JButton jBtnUploadDegree;
    private javax.swing.JButton jBtnUploadTranscript;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
