/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smiu;

import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Syed Taqi
 */
public class Marks_Entry extends javax.swing.JFrame {

    /**
     * Creates new form FirstSemester
     */
    public Marks_Entry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTexSemester1 = new javax.swing.JTextField();
        jTexICT = new javax.swing.JTextField();
        jTexPF = new javax.swing.JTextField();
        jTexEnglish = new javax.swing.JTextField();
        jTexAP = new javax.swing.JTextField();
        jTexCalculus = new javax.swing.JTextField();
        jTexID = new javax.swing.JTextField();
        jTexName = new javax.swing.JTextField();
        jTexFather = new javax.swing.JTextField();
        jTexCNIC = new javax.swing.JTextField();
        jTexDepartment = new javax.swing.JTextField();
        jBtnSearch = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTexSemester2 = new javax.swing.JTextField();
        jTexDLD = new javax.swing.JTextField();
        jTexOOP = new javax.swing.JTextField();
        jTexFL = new javax.swing.JTextField();
        jTexCPS = new javax.swing.JTextField();
        jTexPS = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("TRANSCRIPT FROM");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Student ID");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Name");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Father Name");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("CNIC");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Department");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Semester 1");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Marks of ICT");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Marks of PF");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Marks of English");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Marks of AP");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Marks of Calculus");

        jTexSemester1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTexICT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTexPF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTexEnglish.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTexAP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTexCalculus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTexID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTexName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTexFather.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTexCNIC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTexDepartment.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jBtnSearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jBtnSearch.setText("Search");
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Semester 2");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Marks of DLD");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Marks of OOP");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Marks of FL");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Marks of CPS");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Marks of PS");

        jTexSemester2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTexDLD.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTexOOP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTexFL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTexCPS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTexPS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBtnClear.setBackground(new java.awt.Color(0, 0, 0));
        jBtnClear.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jBtnClear.setForeground(new java.awt.Color(255, 255, 255));
        jBtnClear.setText("Clear");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTexID)
                            .addComponent(jTexName)
                            .addComponent(jTexFather)
                            .addComponent(jTexCNIC)
                            .addComponent(jTexDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jBtnSearch))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTexSemester1)
                            .addComponent(jTexICT)
                            .addComponent(jTexPF)
                            .addComponent(jTexEnglish)
                            .addComponent(jTexAP, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jTexCalculus))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTexSemester2)
                            .addComponent(jTexDLD)
                            .addComponent(jTexOOP)
                            .addComponent(jTexFL)
                            .addComponent(jTexCPS)
                            .addComponent(jTexPS, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))
                .addContainerGap(123, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnClear)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTexID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTexName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTexFather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTexCNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTexDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTexSemester1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTexSemester2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTexICT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTexDLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTexPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(jTexOOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTexEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTexFL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTexAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTexCPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTexCalculus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jTexPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jBtnClear))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 910, 720));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed
        DataRecords DR = new DataRecords();
        ResultSet rs = DR.searchStudentRecord(jTexID.getText());
        try{
            while(rs.next()){
                String data[] = {rs.getString("Name"),rs.getString("Father"),rs.getString("CNIC"),rs.getString("Department")};
                jTexName.setText(data[0]);
                jTexFather.setText(data[1]);
                jTexCNIC.setText(data[2]);
                jTexDepartment.setText(data[3]);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jBtnSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int Total_Subject_Marks = 100;
        int Total_Marks = Total_Subject_Marks*5;
        int Grand_Total_Marks = Total_Subject_Marks*10; 
        String Credit_Hour = "30";
                
        int ICT = Integer.parseInt(jTexICT.getText()), PF = Integer.parseInt(jTexPF.getText()), E = Integer.parseInt(jTexEnglish.getText()), C = Integer.parseInt(jTexCalculus.getText()),A = Integer.parseInt(jTexAP.getText());
        
        int DLD = Integer.parseInt(jTexDLD.getText()), OOP = Integer.parseInt(jTexOOP.getText()), FL = Integer.parseInt(jTexFL.getText()),CPS = Integer.parseInt(jTexCPS.getText()), PS = Integer.parseInt(jTexPS.getText());
        
        double IGPA = 0.00, PGPA = 0.00,EGPA = 0.00,CGPA = 0.00, AGPA = 0.00;
        
        double DGPA = 0.00, OGPA = 0.00, FGPA = 0.00, CPSGPA = 0.00, PSGPA = 0.00;
        
        if(ICT<50){IGPA = 0.00;} if(PF<50){PGPA = 0.00;} if(E<50){EGPA = 0.00;} if(C<50){CGPA = 0.00;} if(A<50){AGPA = 0.00;}
        if(ICT>=50 && ICT <=53){IGPA = 1.00;} if(PF>=50 && PF <=53){PGPA = 1.00;} if(E>=50 && E <=53){EGPA = 1.00;} if(A>=50 && A<=53){AGPA = 1.00;} if(C>=50 && C<=53){CGPA = 1.00;} 
        if(ICT>=54 && ICT <=57){IGPA = 1.33;} if(PF>=54 && PF <=57){PGPA = 1.33;} if(E>=54 && E <=57){EGPA = 1.33;} if(A>=54 && A<=57){AGPA = 1.33;} if(C>=55 && C<=57){CGPA = 1.33;}
        if(ICT>=58 && ICT <=60){IGPA = 1.66;} if(PF>=58 && PF <=60){PGPA = 1.66;} if(E>=58 && E <=60){EGPA = 1.66;} if(A>=58 && A<=60){AGPA = 1.66;} if(C>=58 && C<=60){CGPA = 1.66;}
        if(ICT>=61 && ICT <=63){IGPA = 2.00;} if(PF>=61 && PF <=63){PGPA = 2.00;} if(E>=61 && E <=63){EGPA = 2.00;} if(A>=61 && A<=63){AGPA = 2.00;} if(C>=61 && C<=63){CGPA = 2.00;}
        if(ICT>=64 && ICT <=67){IGPA = 2.33;} if(PF>=64 && PF <=67){PGPA = 2.33;} if(E>=64 && E <=67){EGPA = 2.33;} if(A>=64 && A<=67){AGPA = 2.33;} if(C>=64 && C<=67){CGPA = 2.33;}
        if(ICT>=68 && ICT <=70){IGPA = 2.66;} if(PF>=68 && PF <=70){PGPA = 2.66;} if(E>=68 && E <=70){EGPA = 2.66;} if(A>=68 && A<=70){AGPA = 2.66;} if(C>=68 && C<=70){CGPA = 2.66;} 
        if(ICT>=71 && ICT <=74){IGPA = 3.00;} if(PF>=71 && PF <=74){PGPA = 3.00;} if(E>=71 && E <=74){EGPA = 3.00;} if(A>=71 && A<=74){AGPA = 3.00;} if(C>=71 && C<=74){CGPA = 3.00;}
        if(ICT>=75 && ICT <=79){IGPA = 3.33;} if(PF>=75 && PF <=79){PGPA = 3.33;} if(E>=75 && E <=79){EGPA = 3.33;} if(A>=75 && A<=79){AGPA = 3.33;} if(C>=75 && C<=79){CGPA = 3.33;}
        if(ICT>=80 && ICT <=90){IGPA = 3.66;} if(PF>=80 && PF <=90){PGPA = 3.66;} if(E>=80 && E <=90){EGPA = 3.66;} if(A>=80 && A<=90){AGPA = 3.66;} if(C>=80 && C<=90){CGPA = 3.66;}
        if(ICT>=91 && ICT <=100){IGPA = 4.00;} if(PF>=91 && PF <=100){PGPA = 4.00;} if(E>=91 && E <=100){EGPA = 4.00;} if(A>=91 && A<=100){AGPA = 4.00;} if(C>=91 && C<=100){CGPA = 4.00;}
        
        if(DLD<50){DGPA = 0.00;} if(OOP<50){OGPA = 0.00;} if(FL<50){FGPA = 0.00;} if(CPS<50){CPSGPA = 0.00;} if(PS<50){PSGPA = 0.00;}
        if(DLD>=50 && DLD <=53){DGPA = 1.00;} if(OOP>=50 && OOP <=53){OGPA = 1.00;} if(FL>=50 && FL<=53){FGPA = 1.00;} if(CPS>=50 && CPS<=53){CPSGPA = 1.00;} if(PS>=50 && PS<=53){PSGPA = 1.00;} 
        if(DLD>=54 && DLD <=57){DGPA = 1.33;} if(OOP>=54 && OOP <=57){OGPA = 1.33;} if(FL>=54 && FL<=57){FGPA = 1.33;} if(CPS>=54 && CPS<=57){CPSGPA = 1.33;} if(PS>=55 && PS<=57){PSGPA = 1.33;}
        if(DLD>=58 && DLD <=60){DGPA = 1.66;} if(OOP>=58 && OOP <=60){OGPA = 1.66;} if(FL>=58 && FL<=60){FGPA = 1.66;} if(CPS>=58 && CPS<=60){CPSGPA = 1.66;} if(PS>=58 && PS<=60){PSGPA = 1.66;}
        if(DLD>=61 && DLD <=63){DGPA = 2.00;} if(OOP>=61 && OOP <=63){OGPA = 2.00;} if(FL>=61 && FL<=63){FGPA = 2.00;} if(CPS>=61 && CPS<=63){CPSGPA = 2.00;} if(PS>=61 && PS<=63){PSGPA = 2.00;}
        if(DLD>=64 && DLD <=67){DGPA = 2.33;} if(OOP>=64 && OOP <=67){OGPA = 2.33;} if(FL>=64 && FL<=67){FGPA = 2.33;} if(CPS>=64 && CPS<=67){CPSGPA = 2.33;} if(PS>=64 && PS<=67){PSGPA = 2.33;}
        if(DLD>=68 && DLD <=70){DGPA = 2.66;} if(OOP>=68 && OOP <=70){OGPA = 2.66;} if(FL>=68 && FL<=70){FGPA = 2.66;} if(CPS>=68 && CPS<=70){CPSGPA = 2.66;} if(PS>=68 && PS<=70){PSGPA = 2.66;} 
        if(DLD>=71 && DLD <=74){DGPA = 3.00;} if(OOP>=71 && OOP <=74){OGPA = 3.00;} if(FL>=71 && FL<=74){FGPA = 3.00;} if(CPS>=71 && CPS<=74){CPSGPA = 3.00;} if(PS>=71 && PS<=74){PSGPA = 3.00;}
        if(DLD>=75 && DLD <=79){DGPA = 3.33;} if(OOP>=75 && OOP <=79){OGPA = 3.33;} if(FL>=75 && FL<=79){FGPA = 3.33;} if(CPS>=75 && CPS<=79){CPSGPA = 3.33;} if(PS>=75 && PS<=79){PSGPA = 3.33;}
        if(DLD>=80 && DLD <=90){DGPA = 3.66;} if(OOP>=80 && OOP <=90){OGPA = 3.66;} if(FL>=80 && FL<=90){FGPA = 3.66;} if(CPS>=80 && CPS<=90){CPSGPA = 3.66;} if(PS>=80 && PS<=90){PSGPA = 3.66;}
        if(DLD>=91 && DLD <=100){DGPA = 4.00;} if(OOP>=91 && OOP <=100){OGPA = 4.00;} if(FL>=91 && FL<=100){FGPA = 4.00;} if(CPS>=91 && CPS<=100){CPSGPA = 4.00;} if(PS>=91 && PS<=100){PSGPA = 4.00;}
        
        int Total_1 = ICT + PF + E + C + A;
        double GPA_1 = (IGPA + PGPA + EGPA + CGPA + AGPA)/5.0;
        
        int Total_2 = DLD + OOP + FL + CPS + PS;
        double GPA_2 = (DGPA + OGPA + FGPA + CPSGPA + PSGPA)/5.0;
        
        int Grand_total = Total_1 + Total_2;
        double GPA = (GPA_1 + GPA_2)/2.0;
        
        DecimalFormat output = new DecimalFormat("0.00"); 
        Transcript Info = new Transcript();
        Info.jTexTranscript.setText("\t       Sindh Madressatul Islam University, Karachi \n\t\t\t       Transcript\n"+
        " -------------------------------------------------------------------" + "\n Name: "+jTexName.getText() + "\t\t| " + "Father Name: " + jTexFather.getText()+
        "\n -------------------------------------------------------------------" + "\n Student ID: "+jTexID.getText() + "\t| " + "CNIC: " + jTexCNIC.getText()+
        "\n -------------------------------------------------------------------" + "\n Department: "+jTexDepartment.getText() + "\t| " + "No.of Credit Hour: " + "30"+
        "\n -------------------------------------------------------------------" + "\n\n -------------------------------------------------------------------"+
        "\n Semester 1\t\t     "+jTexSemester1.getText()+"\n -------------------------------------------------------------------"+ "\n Course           | Obt.Marks | Max.Marks | Credit.H | Grade Point |"
        +"\n -------------------------------------------------------------------"+
        "\n ICT              |     " + ICT+ "    |    " + Total_Subject_Marks + "    |" + "     3    |     " + output.format(IGPA) + "    |"+
        "\n PF               |     " + PF+ "    |    " + Total_Subject_Marks + "    |" + "     3    |     " + output.format(PGPA) + "    |" +
        "\n English          |     " + E+ "    |    " + Total_Subject_Marks + "    |" + "     3    |     " + output.format(EGPA) + "    |" +
        "\n Calculus         |     " + C+ "    |    " + Total_Subject_Marks + "    |" + "     3    |     " + output.format(CGPA) + "    |"+ 
        "\n Applied Physics  |     " + A+ "    |    " + Total_Subject_Marks + "    |" + "     3    |     " + output.format(AGPA) + "    |" +
        "\n -------------------------------------------------------------------"+
        "\n            Total |     " + Total_1+ "   |    " + Total_Marks + "    |" + "      GPA |     " +output.format(GPA_1) + "    |" +
        "\n -------------------------------------------------------------------"+
        "\n      Grand_Total |     " + Total_1+ "   |    " + Total_Marks + "    |" + "     CGPA |     " +output.format(GPA_1) + "    |" +
        "\n -------------------------------------------------------------------"+
        "\n\n -------------------------------------------------------------------"+        
        "\n Semester 2\t\t     "+jTexSemester2.getText()+"\n -------------------------------------------------------------------"+ "\n Course           | Obt.Marks | Max.Marks | Credit.H | Grade Point |"
        +"\n -------------------------------------------------------------------"+
        "\n DLD              |     " + DLD+ "    |    " + Total_Subject_Marks + "    |" + "     3    |     " + output.format(DGPA) + "    |"+
        "\n OOP              |     " + OOP+ "    |    " + Total_Subject_Marks + "    |" + "     3    |     " + output.format(OGPA) + "    |" +
        "\n Foreign Language |     " + FL+ "    |    " + Total_Subject_Marks + "    |" + "     3    |     " + output.format(FGPA) + "    |" +
        "\n Com & Pres Skill |     " + CPS+ "    |    " + Total_Subject_Marks + "    |" + "     3    |     " + output.format(CPSGPA) + "    |"+ 
        "\n Prob & Stats     |     " + PS+ "    |    " + Total_Subject_Marks + "    |" + "     3    |     " + output.format(PSGPA) + "    |" +
        "\n -------------------------------------------------------------------"+
        "\n            Total |     " + Total_2+ "   |    " + Total_Marks + "    |" + "      GPA |     " +output.format(GPA_2) + "    |" +
        "\n -------------------------------------------------------------------"+
        "\n      Grand_Total |     " + Grand_total+ "   |   " +Grand_Total_Marks+ "    |" + "     CGPA |     " +output.format(GPA) + "    |" +
        "\n -------------------------------------------------------------------"
        );
        Info.jTexId.setText(jTexID.getText());
        DataRecords DR = new DataRecords();
        try{
            DR.insertFirstSemesterMarks(jTexID.getText(), jTexICT.getText(), jTexPF.getText(), jTexEnglish.getText(), jTexCalculus.getText(), jTexAP.getText());
            DR.insertSecondSemesterMarks(jTexID.getText(), jTexDLD.getText(), jTexOOP.getText(), jTexFL.getText(), jTexCPS.getText(), jTexPS.getText());
            if(ICT>=50&&PF>=50&&E>=50&&A>=50&&C>=50&&DLD>=50&&OOP>=50&&FL>=50&&PF>=50&&CPS>=50&&PS>=50){
            String Grade = "Pass";
            String Summer = "No";
            String Total_GPA = String.valueOf(GPA);
            DR.insertDegreeRecords(jTexID.getText(), jTexName.getText(), Credit_Hour, Grade, Total_GPA, Summer, jTexDepartment.getText());
            }
            else{
            String Grade = "Fail";
            String Summer = "Yes";
            String Total_GPA = String.valueOf(GPA);
            DR.insertDegreeRecords(jTexID.getText(), jTexName.getText(), Credit_Hour, Grade, Total_GPA, Summer, jTexDepartment.getText());
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        Info.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
       
    }//GEN-LAST:event_jBtnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marks_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marks_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marks_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marks_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marks_Entry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTexAP;
    private javax.swing.JTextField jTexCNIC;
    private javax.swing.JTextField jTexCPS;
    private javax.swing.JTextField jTexCalculus;
    private javax.swing.JTextField jTexDLD;
    private javax.swing.JTextField jTexDepartment;
    private javax.swing.JTextField jTexEnglish;
    private javax.swing.JTextField jTexFL;
    private javax.swing.JTextField jTexFather;
    private javax.swing.JTextField jTexICT;
    public static javax.swing.JTextField jTexID;
    private javax.swing.JTextField jTexName;
    private javax.swing.JTextField jTexOOP;
    private javax.swing.JTextField jTexPF;
    private javax.swing.JTextField jTexPS;
    private javax.swing.JTextField jTexSemester1;
    private javax.swing.JTextField jTexSemester2;
    // End of variables declaration//GEN-END:variables

    private void DecimalFormat(double IGPA) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
