/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smiu;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Syed Taqi
 */
public class RegisterForm extends javax.swing.JFrame {
    
    public void clear(){
        jTexName.setText("");
        jTexFatherName.setText("");
        jTexID.setText("");
        jTexPassword.setText("");
        jTexConfirmPassword.setText("");
        jTexPhoneNo.setText("");
        jTexEmail.setText("");
        jTexCNIC.setText("");
        jRBMale.setSelected(false);
        jRBFemale.setSelected(false);
    }
    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jBtnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTexName = new javax.swing.JTextField();
        jTexID = new javax.swing.JTextField();
        jTexPhoneNo = new javax.swing.JTextField();
        jTexEmail = new javax.swing.JTextField();
        jCBDepartment = new javax.swing.JComboBox<>();
        jTexPassword = new javax.swing.JPasswordField();
        jTexConfirmPassword = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jRB2Show = new javax.swing.JRadioButton();
        jRB1Show = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRBMale = new javax.swing.JRadioButton();
        jRBFemale = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jTexFatherName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTexCNIC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(0, 0, 0)));

        jBtnSubmit.setBackground(new java.awt.Color(0, 0, 0));
        jBtnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSubmit.setText("SUBMIT");
        jBtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubmitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("SMIU Registration Form");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Student ID");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Confirm Password");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Phone Number");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Email");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Department");

        jTexName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTexID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTexPhoneNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTexEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jCBDepartment.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jCBDepartment.setMaximumRowCount(10);
        jCBDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Software Engineering", "Business Administration", "Accounting Banking & Finance", "Artificial Intelligence & Mathematical Sciences", "Media and Communication Studies", "English", "Social Development", "Education", "Environmental Sciences" }));

        jTexPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTexConfirmPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jRB2Show.setBackground(new java.awt.Color(255, 255, 255));
        jRB2Show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ShowPassword.jpeg"))); // NOI18N
        jRB2Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB2ShowActionPerformed(evt);
            }
        });

        jRB1Show.setBackground(new java.awt.Color(255, 255, 255));
        jRB1Show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ShowPassword.jpeg"))); // NOI18N
        jRB1Show.setPreferredSize(new java.awt.Dimension(51, 60));
        jRB1Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB1ShowActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Gender");

        buttonGroup1.add(jRBMale);
        jRBMale.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRBMale.setText("Male");

        buttonGroup1.add(jRBFemale);
        jRBFemale.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRBFemale.setText("Female");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Father Name");

        jTexFatherName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("CNIC");

        jTexCNIC.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTexCNIC.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnSubmit)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRBMale)
                                .addGap(33, 33, 33)
                                .addComponent(jRBFemale))
                            .addComponent(jCBDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTexPhoneNo)
                            .addComponent(jTexConfirmPassword)
                            .addComponent(jTexPassword)
                            .addComponent(jTexID)
                            .addComponent(jTexFatherName)
                            .addComponent(jTexName)
                            .addComponent(jTexEmail)
                            .addComponent(jTexCNIC))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRB2Show, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRB1Show, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTexName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTexFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTexID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTexPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRB1Show, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRB2Show, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTexConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTexPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTexEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTexCNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCBDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jRBMale)
                    .addComponent(jRBFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSubmit)
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 590, 690));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRB1ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB1ShowActionPerformed
        if(jRB1Show.isSelected()){
         jTexPassword.setEchoChar((char)0);
         }
         else
         {
         jTexPassword.setEchoChar('*');
         }
    }//GEN-LAST:event_jRB1ShowActionPerformed

    private void jRB2ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB2ShowActionPerformed
        if(jRB2Show.isSelected()){
         jTexConfirmPassword.setEchoChar((char)0);
         }
         else
         {
         jTexConfirmPassword.setEchoChar('*');
         }
    }//GEN-LAST:event_jRB2ShowActionPerformed

    private void jBtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubmitActionPerformed
        Calendar timer = Calendar.getInstance(); 
        timer.getTime();
        SimpleDateFormat tDate = new SimpleDateFormat("yyyy");
        String Batch = tDate.format(timer.getTime());
        String Name = jTexName.getText();
        String Father = jTexFatherName.getText();
        String ID = jTexID.getText();
        String Password = String.valueOf(jTexPassword.getPassword());
        String ConfirmPassword =  String.valueOf(jTexConfirmPassword.getPassword());
        String PhoneNo = jTexPhoneNo.getText();
        String Email = jTexEmail.getText();
        String CNIC = jTexCNIC.getText();
        String Department = (String)jCBDepartment.getSelectedItem();
        String Gender1 = "Male";
        String Gender2 = "Female";
        String Status1 = "Not Issue";
        String Status2 = "Not Issue";
        
        DataRecords DR = new DataRecords();
             try{
                 if(Password.equals(ConfirmPassword)){
                     if(jRBMale.isSelected() == true){
                     DR.insertStudentRecord(Name,Father,ID,Password,PhoneNo,Email,CNIC,Gender1,Department,Batch,Status1,Status2);
                     JOptionPane.showMessageDialog(this, "Submit Successfully!");
                     clear();
                     jRBFemale.setSelected(false);
                     }
                     if(jRBFemale.isSelected() == true){
                     DR.insertStudentRecord(Name,Father,ID,Password,PhoneNo,Email,CNIC,Gender2,Department,Batch,Status1,Status2);
                     JOptionPane.showMessageDialog(this, "Submit Successfully!");
                     clear();
                     jRBMale.setSelected(false);
                     }
                 }
                 else{
                 JOptionPane.showMessageDialog(this, "Your Passwords are not match");
                 jTexPassword.setText("");
                 jTexConfirmPassword.setText("");
                 }
             }
             catch(Exception e){
                 System.out.println(e);
             }
    }//GEN-LAST:event_jBtnSubmitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Calendar timer = Calendar.getInstance(); 
        timer.getTime();
        SimpleDateFormat tDate = new SimpleDateFormat("yy");
        String Date = tDate.format(timer.getTime());
        jTexID.setText("CSC-"+Date+"F-");
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnSubmit;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCBDepartment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRB1Show;
    private javax.swing.JRadioButton jRB2Show;
    private javax.swing.JRadioButton jRBFemale;
    private javax.swing.JRadioButton jRBMale;
    private javax.swing.JTextField jTexCNIC;
    private javax.swing.JPasswordField jTexConfirmPassword;
    private javax.swing.JTextField jTexEmail;
    private javax.swing.JTextField jTexFatherName;
    private javax.swing.JTextField jTexID;
    private javax.swing.JTextField jTexName;
    private javax.swing.JPasswordField jTexPassword;
    private javax.swing.JTextField jTexPhoneNo;
    // End of variables declaration//GEN-END:variables
}
