/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smiu;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Syed Taqi
 */
public class StudentPage extends javax.swing.JFrame {

    /**
     * Creates new form StudentPage
     */
    public StudentPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ShowTranscript = new javax.swing.JButton();
        ViewMarsks = new javax.swing.JButton();
        ShowDegree = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(0, 0, 0)));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SMIU.jpg"))); // NOI18N
        jLabel2.setToolTipText("");

        ShowTranscript.setBackground(new java.awt.Color(0, 0, 0));
        ShowTranscript.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ShowTranscript.setForeground(new java.awt.Color(255, 255, 255));
        ShowTranscript.setText("SHOW TRANSCRIPT");
        ShowTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTranscriptActionPerformed(evt);
            }
        });

        ViewMarsks.setBackground(new java.awt.Color(0, 0, 0));
        ViewMarsks.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ViewMarsks.setForeground(new java.awt.Color(255, 255, 255));
        ViewMarsks.setText("VIEW MARKS");
        ViewMarsks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMarsksActionPerformed(evt);
            }
        });

        ShowDegree.setBackground(new java.awt.Color(0, 0, 0));
        ShowDegree.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ShowDegree.setForeground(new java.awt.Color(255, 255, 255));
        ShowDegree.setText("SHOW DEGREE");
        ShowDegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDegreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ShowDegree)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ViewMarsks)
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ShowTranscript)
                        .addGap(159, 159, 159))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(ShowTranscript)
                .addGap(81, 81, 81)
                .addComponent(ViewMarsks)
                .addGap(79, 79, 79)
                .addComponent(ShowDegree)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 740, 750));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 840));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTranscriptActionPerformed
        String ID = jTextField1.getText();
        ShowTranscript Info = new ShowTranscript();
        DataRecords DR = new DataRecords();
        try{
            ResultSet rs = DR.searchTranscriptRecord(ID);
            while(rs.next()){
                String data[]={rs.getString("ID"),rs.getString("Transcript")};
                Info.jTexTranscript.setText(data[1]);
                Info.setVisible(true);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_ShowTranscriptActionPerformed

    private void ViewMarsksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMarsksActionPerformed
        String ID = jTextField1.getText();
        ViewMarks Info = new ViewMarks();
        Info.jTextField1.setText(ID);
        Info.setVisible(true);
    }//GEN-LAST:event_ViewMarsksActionPerformed

    private void ShowDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDegreeActionPerformed
        String ID = jTextField1.getText();
        ShowDegree Info = new ShowDegree();
        DataRecords DR = new DataRecords();
        try{
            ResultSet rs = DR.searchDegreeRecord(ID);
            while(rs.next()){
                String data[]={rs.getString("ID"),rs.getString("Degree")};
                Info.jTexDegree.setText(data[1]);
                Info.setVisible(true);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_ShowDegreeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ShowDegree;
    private javax.swing.JButton ShowTranscript;
    private javax.swing.JButton ViewMarsks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
