/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smiu;

import java.sql.ResultSet;

/**
 *
 * @author Syed Taqi
 */
public class ViewMarks extends javax.swing.JFrame {

    /**
     * Creates new form ViewMarks
     */
    public ViewMarks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jBtnSignout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBtnFallSemester = new javax.swing.JButton();
        jBtnSpringSemester = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 98, 1138, 742));

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));

        jBtnSignout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnSignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        jBtnSignout.setText("SIGN OUT");
        jBtnSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSignoutActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSignout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1219, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Forte", 1, 30)); // NOI18N
        jLabel2.setText("NAVIGATION BAR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, -1, -1));

        jBtnFallSemester.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnFallSemester.setText("FALL SEMESTER");
        jBtnFallSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFallSemesterActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnFallSemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, 288, -1));

        jBtnSpringSemester.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnSpringSemester.setText("SPRING SEMESTER");
        jBtnSpringSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSpringSemesterActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSpringSemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, 288, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSignoutActionPerformed
        StudentPage Info = new StudentPage();
        Info.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnSignoutActionPerformed

    private void jBtnFallSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFallSemesterActionPerformed
        String ID = jTextField1.getText();
        FallSemester Info = new FallSemester();
        DataRecords DR = new DataRecords();
        try{
            ResultSet rs = DR.searchFallSemster(ID);
            while(rs.next()){
                String data[]={rs.getString("ID"),rs.getString("Subject1"),rs.getString("Subject2"),rs.getString("Subject3"),rs.getString("Subject4"),rs.getString("Subject5")};
                Info.jTexICT.setText(data[1]);
                Info.jTexPF.setText(data[2]);
                Info.jTexEnglish.setText(data[3]);
                Info.jTexCalculus.setText(data[4]);
                Info.jTexAP.setText(data[5]);
                Info.setVisible(true);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jBtnFallSemesterActionPerformed

    private void jBtnSpringSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSpringSemesterActionPerformed
        String ID = jTextField1.getText();
        SpringSemester Info = new SpringSemester();
        DataRecords DR = new DataRecords();
        try{
            ResultSet rs = DR.searchSpringSemster(ID);
            while(rs.next()){
                String data[]={rs.getString("ID"),rs.getString("Subject1"),rs.getString("Subject2"),rs.getString("Subject3"),rs.getString("Subject4"),rs.getString("Subject5")};
                Info.jTexDLD.setText(data[1]);
                Info.jTexOOP.setText(data[2]);
                Info.jTexFL.setText(data[3]);
                Info.jTexCPS.setText(data[4]);
                Info.jTexPS.setText(data[5]);
                Info.setVisible(true);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jBtnSpringSemesterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMarks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFallSemester;
    private javax.swing.JButton jBtnSignout;
    private javax.swing.JButton jBtnSpringSemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
